from __future__ import annotations

SECURITY_FAILURES = frozenset(
    {
        "NPC_PERMISSION_DENIED",
        "STEP_TOOL_MISMATCH",
        "STEP_ARGUMENT_MISMATCH",
        "TASK_CONTEXT_MISMATCH",
        "TASK_PLAYER_MISMATCH",
        "TASK_NPC_MISMATCH",
        "STEP_ACTOR_MISMATCH",
        "OFFICER_NOT_APPOINTED",
        "AUTHORITY_POLICY_INVALID",
        "IDEMPOTENCY_KEY_REUSED",
        "WORLD_OPERATION_CONTRACT_VIOLATION",
        "SECURITY_FAILURE_NOT_REPLANNABLE",
    }
)

PLAN_SECURITY_FAILURES = frozenset(
    {
        "PLAN_TASK_MISMATCH",
        "PLAN_NPC_UNAVAILABLE",
        "PLAN_TOOL_UNAUTHORIZED",
        "PLAN_OFFICER_NOT_APPOINTED",
        "PLAN_AUTHORITY_POLICY_INVALID",
    }
)

PLAN_SOURCES = frozenset(
    {
        "DETERMINISTIC_RECOVERY_FALLBACK",
        "MOCK_PLANNER",
        "MODEL_PLANNER",
        "MANUAL",
    }
)

PLANNING_MODES = frozenset({"PROVIDER"})
