from enum import StrEnum


class PlayerStatus(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class NPCRole(StrEnum):
    GUIDE = "GUIDE"
    QUEST_GIVER = "QUEST_GIVER"
    MERCHANT = "MERCHANT"
    ENEMY = "ENEMY"
    BOSS = "BOSS"
    STRATEGIST = "STRATEGIST"
    GENERAL = "GENERAL"
    STEWARD = "STEWARD"


class RelationshipAttitude(StrEnum):
    HOSTILE = "HOSTILE"
    UNFRIENDLY = "UNFRIENDLY"
    NEUTRAL = "NEUTRAL"
    FRIENDLY = "FRIENDLY"
    TRUSTED = "TRUSTED"


class NodeType(StrEnum):
    START = "START"
    NPC = "NPC"
    EVENT = "EVENT"
    ENCOUNTER = "ENCOUNTER"
    REST = "REST"
    BOSS = "BOSS"


class NodeStatus(StrEnum):
    LOCKED = "LOCKED"
    AVAILABLE = "AVAILABLE"
    ENTERED = "ENTERED"
    COMPLETED = "COMPLETED"


class QuestStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    REWARDED = "REWARDED"


class RewardStatus(StrEnum):
    PENDING = "PENDING"
    ELIGIBLE = "ELIGIBLE"
    CLAIMED = "CLAIMED"


class ObjectiveType(StrEnum):
    COMPLETE_NODE = "COMPLETE_NODE"
    COMPLETE_ENCOUNTER = "COMPLETE_ENCOUNTER"
    COLLECT_ITEM = "COLLECT_ITEM"
    REACH_RELATIONSHIP = "REACH_RELATIONSHIP"


class EncounterStatus(StrEnum):
    PENDING = "PENDING"
    ACTIVE = "ACTIVE"
    VICTORY = "VICTORY"
    DEFEAT = "DEFEAT"


class SessionStatus(StrEnum):
    ACTIVE = "ACTIVE"
    CLOSED = "CLOSED"


class MessageRole(StrEnum):
    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class MemoryType(StrEnum):
    PLAYER_PREFERENCE = "PLAYER_PREFERENCE"
    RELATIONSHIP_EVENT = "RELATIONSHIP_EVENT"
    QUEST_EVENT = "QUEST_EVENT"
    WORLD_EVENT = "WORLD_EVENT"
    CONVERSATION_SUMMARY = "CONVERSATION_SUMMARY"


class RunStatus(StrEnum):
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TerminationReason(StrEnum):
    FINAL_RESPONSE = "FINAL_RESPONSE"
    MAX_ROUNDS = "MAX_ROUNDS"
    TOOL_LIMIT = "TOOL_LIMIT"
    MODEL_TIMEOUT = "MODEL_TIMEOUT"
    PROVIDER_ERROR = "PROVIDER_ERROR"
    REPEATED_INVALID_TOOL_CALL = "REPEATED_INVALID_TOOL_CALL"
    SECURITY_REJECTION = "SECURITY_REJECTION"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class AgentTaskStatus(StrEnum):
    ACTIVE = "ACTIVE"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    REQUIRES_PLAYER_DECISION = "REQUIRES_PLAYER_DECISION"
    WAITING_FOR_PLAYER_ACTION = "WAITING_FOR_PLAYER_ACTION"
    WAITING_FOR_WORLD_EVENT = "WAITING_FOR_WORLD_EVENT"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"


class AgentPlanStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"


class AgentStepStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    WAITING_FOR_USER = "WAITING_FOR_USER"
    REQUIRES_PLAYER_DECISION = "REQUIRES_PLAYER_DECISION"
    WAITING_FOR_PLAYER_ACTION = "WAITING_FOR_PLAYER_ACTION"
    WAITING_FOR_WORLD_EVENT = "WAITING_FOR_WORLD_EVENT"
    SKIPPED = "SKIPPED"


class StepExecutionType(StrEnum):
    TOOL = "TOOL"
    WAIT_FOR_USER = "WAIT_FOR_USER"
    WAIT_FOR_PLAYER_ACTION = "WAIT_FOR_PLAYER_ACTION"
    WAIT_FOR_WORLD_EVENT = "WAIT_FOR_WORLD_EVENT"


class AuthorityOutcome(StrEnum):
    ALLOW = "ALLOW"
    REQUIRE_PLAYER_DECISION = "REQUIRE_PLAYER_DECISION"
    DENY = "DENY"


class DecisionStatus(StrEnum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONSUMED = "CONSUMED"


class WorldOperationStatus(StrEnum):
    PENDING = "PENDING"
    RESOLVED = "RESOLVED"
