"""initial_schema

Revision ID: 0001
Revises:
Create Date: 2026-07-27 17:46:48.643003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_runs",
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item_definitions",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("type", sa.String(length=40), nullable=False),
        sa.Column("stackable", sa.Boolean(), nullable=False),
        sa.Column("max_stack", sa.Integer(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("max_stack >= 1", name="ck_item_max_stack"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "quest_templates",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("allowed_roles", sa.JSON(), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("prerequisites", sa.JSON(), nullable=False),
        sa.Column(
            "objective_type",
            sa.Enum(
                "COMPLETE_NODE",
                "COMPLETE_ENCOUNTER",
                "COLLECT_ITEM",
                "REACH_RELATIONSHIP",
                name="objectivetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("objective_target", sa.String(length=100), nullable=False),
        sa.Column("objective_quantity", sa.Integer(), nullable=False),
        sa.Column("reward", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "worlds",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("chapter", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "evaluation_results",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_name", sa.String(length=160), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("expected_code", sa.String(length=100), nullable=False),
        sa.Column("actual_code", sa.String(length=100), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["evaluation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_eval_results_run", "evaluation_results", ["run_id"], unique=False)
    op.create_table(
        "world_nodes",
        sa.Column("world_id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "START",
                "NPC",
                "EVENT",
                "ENCOUNTER",
                "REST",
                "BOSS",
                name="nodetype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "default_status",
            sa.Enum(
                "LOCKED", "AVAILABLE", "ENTERED", "COMPLETED", name="nodestatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["world_id"], ["worlds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("world_id", "key"),
    )
    op.create_table(
        "encounter_definitions",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("allowed_strategies", sa.JSON(), nullable=False),
        sa.Column("success_rules", sa.JSON(), nullable=False),
        sa.Column("reward_template", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["world_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
        sa.UniqueConstraint("node_id"),
    )
    op.create_table(
        "npcs",
        sa.Column("key", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("persona", sa.Text(), nullable=False),
        sa.Column("current_node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "GUIDE",
                "QUEST_GIVER",
                "MERCHANT",
                "ENEMY",
                "BOSS",
                name="npcrole",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("permission_profile", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["current_node_id"],
            ["world_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "players",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("gold", sa.Integer(), nullable=False),
        sa.Column("current_node_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "DISABLED", name="playerstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("gold >= 0", name="ck_player_gold"),
        sa.CheckConstraint("level >= 1", name="ck_player_level"),
        sa.ForeignKeyConstraint(
            ["current_node_id"],
            ["world_nodes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "world_node_edges",
        sa.Column("source_node_id", sa.Uuid(), nullable=False),
        sa.Column("target_node_id", sa.Uuid(), nullable=False),
        sa.Column("prerequisite_type", sa.String(length=40), nullable=True),
        sa.Column("prerequisite_value", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["source_node_id"], ["world_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_node_id"], ["world_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_node_id", "target_node_id"),
    )
    op.create_table(
        "conversation_sessions",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CLOSED", name="sessionstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["npc_id"],
            ["npcs.id"],
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "encounter_runs",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("encounter_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "ACTIVE", "VICTORY", "DEFEAT", name="encounterstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("selected_strategy", sa.String(length=30), nullable=True),
        sa.Column("result", sa.String(length=30), nullable=True),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("settlement_idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["encounter_id"],
            ["encounter_definitions.id"],
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "idempotency_key"),
    )
    op.create_table(
        "inventory_items",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("item_definition_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("quantity >= 0", name="ck_inventory_quantity"),
        sa.ForeignKeyConstraint(
            ["item_definition_id"],
            ["item_definitions.id"],
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_id", "item_definition_id"),
    )
    op.create_table(
        "player_node_states",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "LOCKED", "AVAILABLE", "ENTERED", "COMPLETED", name="nodestatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["node_id"], ["world_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_id", "node_id"),
    )
    op.create_table(
        "player_npc_relationships",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "attitude",
            sa.Enum(
                "HOSTILE",
                "UNFRIENDLY",
                "NEUTRAL",
                "FRIENDLY",
                "TRUSTED",
                name="relationshipattitude",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("score >= -100 AND score <= 100", name="ck_relationship_score"),
        sa.ForeignKeyConstraint(["npc_id"], ["npcs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("player_id", "npc_id"),
    )
    op.create_table(
        "quests",
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("issuer_npc_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AVAILABLE",
                "ACTIVE",
                "COMPLETED",
                "FAILED",
                "REWARDED",
                name="queststatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column(
            "reward_status",
            sa.Enum("PENDING", "ELIGIBLE", "CLAIMED", name="rewardstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("narrative_title", sa.String(length=160), nullable=False),
        sa.Column("narrative_description", sa.Text(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("progress >= 0", name="ck_quest_progress"),
        sa.ForeignKeyConstraint(
            ["issuer_npc_id"],
            ["npcs.id"],
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["quest_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("player_id", "idempotency_key"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("RUNNING", "COMPLETED", "FAILED", name="runstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_message", sa.Text(), nullable=False),
        sa.Column("context_record_ids", sa.JSON(), nullable=False),
        sa.Column("model_rounds", sa.JSON(), nullable=False),
        sa.Column("max_rounds", sa.Integer(), nullable=False),
        sa.Column("actual_rounds", sa.Integer(), nullable=False),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "termination_reason",
            sa.Enum(
                "FINAL_RESPONSE",
                "MAX_ROUNDS",
                "TOOL_LIMIT",
                "MODEL_TIMEOUT",
                "PROVIDER_ERROR",
                "REPEATED_INVALID_TOOL_CALL",
                "SECURITY_REJECTION",
                "INTERNAL_ERROR",
                name="terminationreason",
                native_enum=False,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_agent_runs_session_started", "agent_runs", ["session_id", "started_at"], unique=False
    )
    op.create_table(
        "conversation_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SYSTEM", "USER", "ASSISTANT", "TOOL", name="messagerole", native_enum=False),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=True),
        sa.Column("token_usage", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_messages_session_created",
        "conversation_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "memories",
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("npc_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "PLAYER_PREFERENCE",
                "RELATIONSHIP_EVENT",
                "QUEST_EVENT",
                "WORLD_EVENT",
                "CONVERSATION_SUMMARY",
                name="memorytype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance", sa.Integer(), nullable=False),
        sa.Column("source_session_id", sa.Uuid(), nullable=True),
        sa.Column("source_event_id", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["npc_id"],
            ["npcs.id"],
        ),
        sa.ForeignKeyConstraint(["player_id"], ["players.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_session_id"],
            ["conversation_sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_memories_player_npc_importance",
        "memories",
        ["player_id", "npc_id", "importance"],
        unique=False,
    )
    op.create_table(
        "tool_executions",
        sa.Column("agent_run_id", sa.Uuid(), nullable=False),
        sa.Column("tool_call_id", sa.String(length=160), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("validation_status", sa.String(length=30), nullable=False),
        sa.Column("authorization_status", sa.String(length=30), nullable=False),
        sa.Column("business_rule_status", sa.String(length=30), nullable=False),
        sa.Column("execution_status", sa.String(length=30), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["agent_run_id"], ["agent_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_run_id", "tool_call_id"),
    )
    op.create_index(
        "ix_tool_execution_run_created",
        "tool_executions",
        ["agent_run_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tool_execution_run_created", table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index("ix_memories_player_npc_importance", table_name="memories")
    op.drop_table("memories")
    op.drop_index("ix_messages_session_created", table_name="conversation_messages")
    op.drop_table("conversation_messages")
    op.drop_index("ix_agent_runs_session_started", table_name="agent_runs")
    op.drop_table("agent_runs")
    op.drop_table("quests")
    op.drop_table("player_npc_relationships")
    op.drop_table("player_node_states")
    op.drop_table("inventory_items")
    op.drop_table("encounter_runs")
    op.drop_table("conversation_sessions")
    op.drop_table("world_node_edges")
    op.drop_table("players")
    op.drop_table("npcs")
    op.drop_table("encounter_definitions")
    op.drop_table("world_nodes")
    op.drop_index("ix_eval_results_run", table_name="evaluation_results")
    op.drop_table("evaluation_results")
    op.drop_table("worlds")
    op.drop_table("quest_templates")
    op.drop_table("item_definitions")
    op.drop_table("evaluation_runs")
    # ### end Alembic commands ###
