"""strategic command initial schema

Revision ID: d0b3e5ceb9a2
Revises:
Create Date: 2026-08-11 17:21:12.210512
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd0b3e5ceb9a2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('world_nodes',
    sa.Column('world_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('START', 'NPC', 'EVENT', 'ENCOUNTER', name='nodetype', native_enum=False), nullable=False),
    sa.Column('default_status', sa.Enum('LOCKED', 'AVAILABLE', 'ENTERED', 'COMPLETED', name='nodestatus', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('world_id', 'key')
    )
    op.create_table('npcs',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('persona', sa.Text(), nullable=False),
    sa.Column('doctrine', sa.JSON(), nullable=False),
    sa.Column('authority_limits', sa.JSON(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('STRATEGIST', 'GENERAL', 'STEWARD', name='npcrole', native_enum=False), nullable=False),
    sa.Column('permission_profile', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['current_node_id'], ['world_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('players',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('gold', sa.Integer(), nullable=False),
    sa.Column('current_node_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='playerstatus', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('gold >= 0', name='ck_player_gold'),
    sa.CheckConstraint('level >= 1', name='ck_player_level'),
    sa.ForeignKeyConstraint(['current_node_id'], ['world_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_sessions',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('officer_appointments',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('authority_overrides', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'npc_id')
    )
    op.create_table('player_domain_states',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('soldiers_total', sa.Integer(), nullable=False),
    sa.Column('soldiers_committed', sa.Integer(), nullable=False),
    sa.Column('food', sa.Integer(), nullable=False),
    sa.Column('morale', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('food >= 0', name='ck_domain_food'),
    sa.CheckConstraint('morale >= 0 AND morale <= 100', name='ck_domain_morale'),
    sa.CheckConstraint('soldiers_committed >= 0 AND soldiers_committed <= soldiers_total', name='ck_domain_soldiers_committed'),
    sa.CheckConstraint('soldiers_total >= 0', name='ck_domain_soldiers_total'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('player_node_states',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('LOCKED', 'AVAILABLE', 'ENTERED', 'COMPLETED', name='nodestatus', native_enum=False), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['world_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'node_id')
    )
    op.create_table('player_world_facts',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'key')
    )
    op.create_table('agent_tasks',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('owner_npc_id', sa.Uuid(), nullable=False),
    sa.Column('origin_session_id', sa.Uuid(), nullable=False),
    sa.Column('last_session_id', sa.Uuid(), nullable=False),
    sa.Column('goal_description', sa.Text(), nullable=False),
    sa.Column('scenario_key', sa.String(length=100), nullable=False),
    sa.Column('planning_mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REQUIRES_PLAYER_DECISION', 'WAITING_FOR_PLAYER_ACTION', 'WAITING_FOR_WORLD_EVENT', 'SUCCEEDED', 'FAILED', 'BLOCKED', name='agenttaskstatus', native_enum=False, length=30), nullable=False),
    sa.Column('current_plan_version', sa.Integer(), nullable=False),
    sa.Column('replan_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['origin_session_id'], ['conversation_sessions.id'], ),
    sa.ForeignKeyConstraint(['owner_npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_tasks_player_status', 'agent_tasks', ['player_id', 'status'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('SYSTEM', 'USER', 'ASSISTANT', 'TOOL', name='messagerole', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_session_created', 'conversation_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('memories',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('npc_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('WORLD_EVENT', name='memorytype', native_enum=False), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('source_session_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_player_npc_importance', 'memories', ['player_id', 'npc_id', 'importance'], unique=False)
    op.create_table('agent_plans',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUPERSEDED', 'SUCCEEDED', 'FAILED', name='agentplanstatus', native_enum=False), nullable=False),
    sa.Column('strategy_summary', sa.Text(), nullable=False),
    sa.Column('replan_reason', sa.String(length=160), nullable=True),
    sa.Column('supersedes_plan_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_npc_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('planner_model', sa.String(length=100), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_npc_id'], ['npcs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_plan_id'], ['agent_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'version')
    )
    op.create_index('ix_agent_plans_task_version', 'agent_plans', ['task_id', 'version'], unique=False)
    op.create_table('agent_steps',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('execution_type', sa.Enum('TOOL', 'WAIT_FOR_PLAYER_ACTION', 'WAIT_FOR_WORLD_EVENT', name='stepexecutiontype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCEEDED', 'FAILED', 'BLOCKED', 'REQUIRES_PLAYER_DECISION', 'WAITING_FOR_PLAYER_ACTION', 'WAITING_FOR_WORLD_EVENT', 'SKIPPED', name='agentstepstatus', native_enum=False, length=30), nullable=False),
    sa.Column('assigned_npc_id', sa.Uuid(), nullable=True),
    sa.Column('action_intent', sa.String(length=100), nullable=True),
    sa.Column('constraints', sa.JSON(), nullable=False),
    sa.Column('allowed_tool_names', sa.JSON(), nullable=False),
    sa.Column('selected_tool_name', sa.String(length=100), nullable=True),
    sa.Column('tool_arguments', sa.JSON(), nullable=False),
    sa.Column('expected_outcome', sa.JSON(), nullable=False),
    sa.Column('actual_result', sa.JSON(), nullable=True),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('resume_condition', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_npc_id'], ['npcs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['agent_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'sequence')
    )
    op.create_index(op.f('ix_agent_steps_assigned_npc_id'), 'agent_steps', ['assigned_npc_id'], unique=False)
    op.create_index('ix_agent_steps_plan_sequence', 'agent_steps', ['plan_id', 'sequence'], unique=False)
    op.create_table('agent_runs',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_message', sa.Text(), nullable=False),
    sa.Column('context_record_ids', sa.JSON(), nullable=False),
    sa.Column('model_rounds', sa.JSON(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('actual_rounds', sa.Integer(), nullable=False),
    sa.Column('token_usage', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('termination_reason', sa.Enum('FINAL_RESPONSE', 'MAX_ROUNDS', 'TOOL_LIMIT', 'MODEL_TIMEOUT', 'PROVIDER_ERROR', 'REPEATED_INVALID_TOOL_CALL', 'SECURITY_REJECTION', 'INTERNAL_ERROR', name='terminationreason', native_enum=False), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('actor_npc_id', sa.Uuid(), nullable=True),
    sa.Column('officer_profile_version', sa.Integer(), nullable=True),
    sa.Column('authority_policy_version', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('structured_output', sa.JSON(), nullable=True),
    sa.Column('validation_status', sa.String(length=30), nullable=True),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_npc_id'], ['npcs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['agent_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_session_started', 'agent_runs', ['session_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_task_id'), 'agent_runs', ['task_id'], unique=False)
    op.create_table('player_decision_requests',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_npc_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CONSUMED', name='decisionstatus', native_enum=False), nullable=False),
    sa.Column('decision_kind', sa.String(length=30), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('action_tool_name', sa.String(length=100), nullable=False),
    sa.Column('action_arguments', sa.JSON(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON(), nullable=False),
    sa.Column('selected_option', sa.String(length=80), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_decisions_task_status', 'player_decision_requests', ['task_id', 'status'], unique=False)
    op.create_table('world_operations',
    sa.Column('player_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('source_step_id', sa.Uuid(), nullable=True),
    sa.Column('officer_npc_id', sa.Uuid(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('target_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='worldoperationstatus', native_enum=False), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('resolution_key', sa.String(length=160), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_npc_id'], ['npcs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_step_id'], ['agent_steps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['agent_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_world_operations_source_step_id'), 'world_operations', ['source_step_id'], unique=False)
    op.create_index(op.f('ix_world_operations_task_id'), 'world_operations', ['task_id'], unique=False)
    op.create_index('ix_world_operations_task_status', 'world_operations', ['task_id', 'status'], unique=False)
    op.create_table('tool_executions',
    sa.Column('agent_run_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.Uuid(), nullable=True),
    sa.Column('tool_call_id', sa.String(length=160), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.String(length=30), nullable=False),
    sa.Column('authorization_status', sa.String(length=30), nullable=False),
    sa.Column('authority_details', sa.JSON(), nullable=True),
    sa.Column('business_rule_status', sa.String(length=30), nullable=False),
    sa.Column('execution_status', sa.String(length=30), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['step_id'], ['agent_steps.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'tool_call_id')
    )
    op.create_index('ix_tool_execution_run_created', 'tool_executions', ['agent_run_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tool_executions_step_id'), 'tool_executions', ['step_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_step_id'), table_name='tool_executions')
    op.drop_index('ix_tool_execution_run_created', table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index('ix_world_operations_task_status', table_name='world_operations')
    op.drop_index(op.f('ix_world_operations_task_id'), table_name='world_operations')
    op.drop_index(op.f('ix_world_operations_source_step_id'), table_name='world_operations')
    op.drop_table('world_operations')
    op.drop_index('ix_decisions_task_status', table_name='player_decision_requests')
    op.drop_table('player_decision_requests')
    op.drop_index(op.f('ix_agent_runs_task_id'), table_name='agent_runs')
    op.drop_index('ix_agent_runs_session_started', table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index('ix_agent_steps_plan_sequence', table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_assigned_npc_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index('ix_agent_plans_task_version', table_name='agent_plans')
    op.drop_table('agent_plans')
    op.drop_index('ix_memories_player_npc_importance', table_name='memories')
    op.drop_table('memories')
    op.drop_index('ix_messages_session_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index('ix_agent_tasks_player_status', table_name='agent_tasks')
    op.drop_table('agent_tasks')
    op.drop_table('player_world_facts')
    op.drop_table('player_node_states')
    op.drop_table('player_domain_states')
    op.drop_table('officer_appointments')
    op.drop_table('conversation_sessions')
    op.drop_table('players')
    op.drop_table('npcs')
    op.drop_table('world_nodes')
    op.drop_table('worlds')
    # ### end Alembic commands ###
