from app.tools.base import Tool
from app.tools.handlers import (
    CreateQuestArgs,
    CreateTaskPlanArgs,
    EmptyArgs,
    EncounterStateArgs,
    GameActionArgs,
    IdempotentArgs,
    InventoryArgs,
    MilitaryOperationArgs,
    OutpostRepairArgs,
    ReconOperationArgs,
    ReplanTaskArgs,
    TradeRouteTestArgs,
    UpdateRelationshipArgs,
    VillageSupportArgs,
    active_quests,
    available_nodes,
    create_task_plan,
    encounter_state,
    game_action,
    grant_access,
    inspect_command_state,
    inspect_task_requirements,
    inventory,
    negotiate_village_support,
    player_state,
    preflight_military_operation,
    preflight_outpost_repair,
    preflight_recon_operation,
    preflight_trade_route_test,
    preflight_village_support,
    prepare_starfire_route,
    quest_create,
    relationship_update,
    replan_task,
    request_npc_assistance,
    restore_outpost,
    start_military_operation,
    start_outpost_repair,
    start_recon_operation,
    start_trade_route_test,
    world_state,
)
from app.tools.registry import ToolRegistry


def build_registry() -> ToolRegistry:
    registry = ToolRegistry()
    for tool in [
        Tool("get_player_state", "Get player level, gold and activity.", EmptyArgs, player_state),
        Tool("get_inventory", "Get the player's inventory.", InventoryArgs, inventory),
        Tool("get_world_state", "Get chapter and current world state.", EmptyArgs, world_state),
        Tool("get_available_nodes", "Get nodes the player can enter.", EmptyArgs, available_nodes),
        Tool("get_active_quests", "Get active quest progress.", EmptyArgs, active_quests),
        Tool(
            "get_encounter_state",
            "Get current encounter state.",
            EncounterStateArgs,
            encounter_state,
        ),
        Tool(
            "update_relationship",
            "Apply a bounded relationship event for this NPC.",
            UpdateRelationshipArgs,
            relationship_update,
            write=True,
            allowed_roles=frozenset({"GUIDE", "QUEST_GIVER", "MERCHANT", "ENEMY", "BOSS"}),
        ),
        Tool(
            "create_quest",
            "Create a quest from an approved template.",
            CreateQuestArgs,
            quest_create,
            write=True,
            allowed_roles=frozenset({"GUIDE", "QUEST_GIVER", "BOSS"}),
        ),
        Tool(
            "propose_game_action",
            "Request one narrowly-scoped validated game action.",
            GameActionArgs,
            game_action,
            write=True,
            allowed_roles=frozenset({"GUIDE", "QUEST_GIVER", "BOSS"}),
        ),
        Tool(
            "inspect_task_requirements",
            "Inspect verified prerequisites for the active long-running task.",
            EmptyArgs,
            inspect_task_requirements,
        ),
        Tool(
            "inspect_command_state",
            "Inspect verified strategic resources and public Starfire command facts.",
            EmptyArgs,
            inspect_command_state,
            allowed_roles=frozenset({"STRATEGIST", "GENERAL", "STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "create_task_plan",
            "Create the first structured, auditable plan for an active task.",
            CreateTaskPlanArgs,
            create_task_plan,
            write=True,
            allowed_roles=frozenset({"GUIDE", "QUEST_GIVER", "STRATEGIST"}),
            require_permission_profile=True,
        ),
        Tool(
            "replan_task",
            "Create a new plan version after a recoverable failure.",
            ReplanTaskArgs,
            replan_task,
            write=True,
            allowed_roles=frozenset({"GUIDE", "QUEST_GIVER", "STRATEGIST"}),
            require_permission_profile=True,
        ),
        Tool(
            "prepare_starfire_route",
            "Open the approved Starfire road route after its quest is issued.",
            IdempotentArgs,
            prepare_starfire_route,
            write=True,
            allowed_roles=frozenset({"GUIDE"}),
            require_permission_profile=True,
        ),
        Tool(
            "request_npc_assistance",
            "Activate approved NPC assistance for the Starfire encounter.",
            IdempotentArgs,
            request_npc_assistance,
            write=True,
            allowed_roles=frozenset({"GUIDE"}),
            require_permission_profile=True,
        ),
        Tool(
            "restore_outpost",
            "Restore Starfire Outpost after the road is verified safe.",
            IdempotentArgs,
            restore_outpost,
            write=True,
            allowed_roles=frozenset({"GUIDE"}),
            require_permission_profile=True,
        ),
        Tool(
            "grant_access",
            "Grant access to an operational Starfire Outpost.",
            IdempotentArgs,
            grant_access,
            write=True,
            allowed_roles=frozenset({"GUIDE"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_recon_operation",
            "Start a bounded reconnaissance operation; the world resolves its outcome later.",
            ReconOperationArgs,
            start_recon_operation,
            preflight=preflight_recon_operation,
            write=True,
            allowed_roles=frozenset({"GENERAL"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_military_operation",
            "Start a bounded military operation without choosing its result.",
            MilitaryOperationArgs,
            start_military_operation,
            preflight=preflight_military_operation,
            write=True,
            allowed_roles=frozenset({"GENERAL"}),
            require_permission_profile=True,
        ),
        Tool(
            "negotiate_village_support",
            "Offer bounded resources in exchange for approved village support.",
            VillageSupportArgs,
            negotiate_village_support,
            preflight=preflight_village_support,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_outpost_repair",
            "Commit bounded resources and start an asynchronous Starfire repair.",
            OutpostRepairArgs,
            start_outpost_repair,
            preflight=preflight_outpost_repair,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_trade_route_test",
            "Start a deterministic northern trade-route test after prerequisites are met.",
            TradeRouteTestArgs,
            start_trade_route_test,
            preflight=preflight_trade_route_test,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
    ]:
        registry.register(tool)
    return registry
