from app.tools.base import Tool
from app.tools.handlers import (
    CreateTaskPlanArgs,
    EmptyArgs,
    MilitaryOperationArgs,
    OutpostRepairArgs,
    ReconOperationArgs,
    ReplanTaskArgs,
    TradeRouteTestArgs,
    VillageSupportArgs,
    create_task_plan,
    inspect_command_state,
    negotiate_village_support,
    preflight_military_operation,
    preflight_outpost_repair,
    preflight_recon_operation,
    preflight_trade_route_test,
    preflight_village_support,
    replan_task,
    start_military_operation,
    start_outpost_repair,
    start_recon_operation,
    start_trade_route_test,
)
from app.tools.registry import ToolRegistry


def build_registry() -> ToolRegistry:
    registry = ToolRegistry()
    for tool in [
        Tool(
            "inspect_command_state",
            "Inspect verified strategic resources and public Starfire command facts.",
            EmptyArgs,
            inspect_command_state,
            allowed_roles=frozenset({"STRATEGIST", "GENERAL", "STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "create_task_plan",
            "Create the first structured, auditable strategic plan.",
            CreateTaskPlanArgs,
            create_task_plan,
            write=True,
            allowed_roles=frozenset({"STRATEGIST"}),
            require_permission_profile=True,
        ),
        Tool(
            "replan_task",
            "Create a new strategic plan version after a recoverable failure.",
            ReplanTaskArgs,
            replan_task,
            write=True,
            allowed_roles=frozenset({"STRATEGIST"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_recon_operation",
            "Start bounded reconnaissance; GameService resolves the outcome later.",
            ReconOperationArgs,
            start_recon_operation,
            preflight=preflight_recon_operation,
            write=True,
            allowed_roles=frozenset({"GENERAL"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_military_operation",
            "Start a bounded military operation without choosing its result.",
            MilitaryOperationArgs,
            start_military_operation,
            preflight=preflight_military_operation,
            write=True,
            allowed_roles=frozenset({"GENERAL"}),
            require_permission_profile=True,
        ),
        Tool(
            "negotiate_village_support",
            "Offer bounded resources for approved village support.",
            VillageSupportArgs,
            negotiate_village_support,
            preflight=preflight_village_support,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_outpost_repair",
            "Commit bounded resources and start asynchronous outpost repair.",
            OutpostRepairArgs,
            start_outpost_repair,
            preflight=preflight_outpost_repair,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
        Tool(
            "start_trade_route_test",
            "Start a deterministic trade-route test after prerequisites are met.",
            TradeRouteTestArgs,
            start_trade_route_test,
            preflight=preflight_trade_route_test,
            write=True,
            allowed_roles=frozenset({"STEWARD"}),
            require_permission_profile=True,
        ),
    ]:
        registry.register(tool)
    return registry
