const labels: Record<string, string> = {
  DRAFT: "草稿",
  PUBLISHED: "已发布",
  ARCHIVED: "已归档",
  ACTIVE: "进行中",
  SUSPENDED: "已暂停",
  FAILED: "失败",
  COMPLETED: "已完成",
  ABORTED: "已放弃",
  NEEDS_PLAYER_INPUT: "等待玩家决定",
  BLOCKED_BY_PLAYER_DECISION: "因玩家决定受阻",
  UNREACHABLE_IN_CURRENT_STATE: "当前状态无法达成",
  MODEL_PLAN_REJECTED: "模型方案未通过验证",
  MODEL_PROVIDER_TIMEOUT: "模型调用超时",
  MODEL_PROVIDER_FAILURE: "模型调用失败",
  PENDING: "待执行",
  CURRENT: "执行中",
  BLOCKED: "受阻",
  ERROR: "错误",
  WARNING: "警告",
  STRUCTURALLY_VALID: "结构有效",
  MINIMUM_RUNNABLE: "最低可运行",
  MINIMUM_PLAYABLE: "最低可游玩",
  PUBLISH_READY: "可发布",
  BLANK: "空白场景",
  EXAMPLE: "示例场景",
  PLAN_EXHAUSTED: "当前方案已执行完毕，需要重新规划",
  ENCOUNTER_DEFEAT: "遭遇战失利",
  PLAYER_REJECTED: "玩家拒绝了提案",
  GENERIC_REPLAN_LIMIT: "已达到重新规划上限",
  UNSUPPORTED: "不支持的目标",
  NEEDS_CLARIFICATION: "需要澄清",
  ACCEPTED: "已接受",
  AVAILABLE: "可用",
  LOCKED: "锁定",
  KNOWN: "已知",
  HIDDEN: "隐藏",
  IMMEDIATE: "立即执行",
  ASYNC: "异步结算",
  PREFLIGHT: "执行前检查",
  RESOLVE: "结算",
  STRING: "文本",
  ENUM: "枚举",
  INTEGER: "整数",
  BOOLEAN: "布尔值",
  ALL: "全部满足",
  ANY: "任一满足",
  NOT: "取反",
  EQ: "等于",
  NE: "不等于",
  LT: "小于",
  LTE: "小于等于",
  GT: "大于",
  GTE: "大于等于",
  LITERAL: "固定值",
  PARAMETER: "参数",
  PLAN: "规划",
  EXECUTE_ACTION: "执行行动",
  INSPECT_STATE: "检查状态",
  FACT_EQUALS: "事实等于",
  FACT_NOT_EQUALS: "事实不等于",
  FACT_IN: "事实属于集合",
  FACT_COMPARE: "事实比较",
  RESOURCE_COMPARE: "资源比较",
  PARAMETER_COMPARE: "参数比较",
  NODE_VISIBLE: "节点可见",
  NODE_ACCESSIBLE: "节点可访问",
  RELATION_EXISTS: "关系存在",
  SET_FACT: "设置事实",
  REVEAL_FACT: "揭示事实",
  HIDE_FACT: "隐藏事实",
  REVEAL_NODE: "揭示节点",
  HIDE_NODE: "隐藏节点",
  SET_NODE_ACCESS: "设置节点访问状态",
  ADJUST_RESOURCE: "调整资源",
  RESERVE_RESOURCE: "预留资源",
  RELEASE_RESOURCE: "释放资源",
  EMIT_OUTCOME: "产生成功结果",
  EMIT_FAILURE: "产生失败结果",
  WRITE_MEMORY_EVENT: "写入记忆事件",
  SOURCE: "来源节点",
  TARGET: "目标节点",
  EXPLICIT: "显式节点",
  CURRENT_TARGET: "当前目标",
};

export const sectionLabels: Record<string, string> = {
  overview: "概览",
  world: "世界",
  actors: "角色与参与者",
  actions: "行动",
  rules: "规则",
  objectives: "目标",
  planning: "规划",
  "initial-state": "初始状态",
  validation: "验证与发布",
};

export const kindLabels: Record<string, string> = {
  node_type: "节点类型",
  node: "节点",
  resource: "资源",
  interaction: "交互能力",
  role: "角色",
  actor: "参与者",
  action: "行动",
  rule: "规则",
  objective: "目标",
};

const fieldLabels: Record<string, string> = {
  key: "稳定键",
  name: "显示名称",
  description: "说明",
  node_type_key: "节点类型",
  initial_access: "初始访问状态",
  initial_visibility: "初始可见性",
  interaction_keys: "交互能力",
  facts: "事实",
  relations: "关系",
  initial_value: "初始值",
  minimum: "最小值",
  maximum: "最大值",
  reservation_supported: "支持预留",
  capabilities: "能力",
  role_key: "角色",
  persona: "人物设定",
  doctrine: "行为准则",
  initial_node_key: "初始节点",
  allowed_action_keys: "允许的行动",
  authority_policy: "权限策略",
  autonomous_limits: "自主权限上限",
  approval_required_values: "需要批准的值",
  required_interaction_key: "所需交互能力",
  execution_mode: "执行方式",
  parameters: "参数",
  allowed_actor_capabilities: "参与者所需能力",
  expected_outcomes: "预期结果",
  planning: "规划元数据",
  terminal_effects: "终局效果",
  supporting_effects: "辅助效果",
  success_outcome_codes: "成功结果代码",
  wait_success_outcome_codes: "等待成功结果代码",
  hints: "规划提示",
  phase: "阶段",
  action_key: "行动",
  priority: "优先级",
  condition: "条件",
  conditions: "子条件",
  effects: "效果",
  kind: "类型",
  operator: "比较方式",
  source: "值来源",
  value: "值",
  values: "可选值",
  fact_key: "事实",
  node_key: "节点",
  resource_key: "资源",
  parameter_key: "参数",
  completion_requirements: "完成要求",
  prerequisites: "前置条件",
  requirements: "要求",
  subsumes: "包含的目标",
  goal_aliases: "目标别名",
  goal_examples: "目标示例",
  accepted_values: "可接受值",
  start_node_key: "起始节点",
  primary_actor_key: "主要参与者",
  goal_resolution: "目标解析",
  instructions: "规划指引",
  recovery_hints: "恢复提示",
  allowed_values: "允许值",
  required: "必填",
  code: "代码",
  success: "是否成功",
  retryable: "可重试",
  outcome_code: "结果代码",
  metadata: "元数据",
  schema_version: "结构版本",
  engine_contract: "引擎契约",
  world: "世界",
  node_types: "节点类型",
  nodes: "节点",
  resources: "资源",
  interactions: "交互能力",
  actors: "角色与参与者",
  roles: "角色",
  actor_profiles: "参与者",
  actions: "行动",
  rules: "规则",
  objectives: "目标",
  initialization: "初始化",
  allow_llm_fallback: "允许模型辅助解析",
  clarification_prompt: "澄清提示",
  relation_type_key: "关系类型",
  source_node_key: "来源节点",
  target_node_key: "目标节点",
  direction: "方向",
  relation_direction: "关系方向",
  amount: "数量",
  literal: "固定值",
  multiplier: "倍数",
  memory_key: "记忆键",
  memory_content: "记忆内容",
  failure_code: "失败代码",
  message: "消息",
};

export function uiLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return labels[value] ?? value.replaceAll("_", " ");
}

export function fieldLabel(value: string): string {
  return fieldLabels[value] ?? value.replaceAll("_", " ");
}

export function stepDescription(value: string): string {
  if (value.startsWith("Execute ")) return `执行：${value.slice(8)}`;
  if (value.startsWith("Wait for ")) return `等待结算：${value.slice(9)}`;
  return value;
}

export function resultLabel(value: string | null): string | null {
  if (!value) return null;
  if (value === "Completed") return "已完成";
  return uiLabel(value.toUpperCase().replaceAll(" ", "_"));
}

const diagnosticLabels: Record<string, string> = {
  SCENARIO_DOCUMENT_SCHEMA_INVALID: "字段结构或类型不符合场景定义要求。",
  SCENARIO_DOCUMENT_SCHEMA_UNSUPPORTED: "不支持此场景结构版本。",
  SCENARIO_ENGINE_CONTRACT_UNAVAILABLE: "当前平台不支持此通用引擎契约。",
  SCENARIO_OBJECTIVE_REQUIRED: "可发布的场景至少需要一个目标。",
  SCENARIO_ACTION_REQUIRED: "可发布的场景至少需要一个行动。",
  SCENARIO_MINIMUM_PLAYABLE_REQUIRED: "没有已结算行动的规划效果能够推进目标要求。",
  SCENARIO_ACTION_WITHOUT_RESOLVE_RULE: "此行动没有对应的结算规则。",
};

export function diagnosticMessage(code: string, fallback: string): string {
  return diagnosticLabels[code] ?? fallback;
}

export function errorText(error: unknown, fallback = "操作失败，请稍后重试。") {
  if (!error || typeof error !== "object") return fallback;
  const code = "code" in error && typeof error.code === "string" ? error.code : null;
  return code ? `${uiLabel(code)}（${code}）` : fallback;
}
