const labels: Record<string, string> = {
  DRAFT: "草稿",
  PUBLISHED: "已发布",
  ARCHIVED: "已归档",
  ACTIVE: "进行中",
  SUSPENDED: "已暂停",
  FAILED: "失败",
  COMPLETED: "已完成",
  ABORTED: "已放弃",
  NEEDS_PLAYER_INPUT: "等待玩家决定",
  BLOCKED_BY_PLAYER_DECISION: "因玩家决定受阻",
  UNREACHABLE_IN_CURRENT_STATE: "当前状态无法达成",
  ACTION_EXECUTION_FAILED: "行动执行失败",
  MODEL_PLAN_REJECTED: "模型方案未通过验证",
  MODEL_PROVIDER_TIMEOUT: "模型调用超时",
  MODEL_PROVIDER_FAILURE: "模型调用失败",
  PENDING: "待执行",
  CURRENT: "执行中",
  BLOCKED: "受阻",
  ERROR: "错误",
  WARNING: "警告",
  STRUCTURALLY_VALID: "结构有效",
  MINIMUM_RUNNABLE: "最低可运行",
  MINIMUM_PLAYABLE: "最低可游玩",
  PUBLISH_READY: "可发布",
  BLANK: "空白场景",
  EXAMPLE: "示例场景",
  PLAN_EXHAUSTED: "当前方案已执行完毕，需要重新规划",
  ENCOUNTER_DEFEAT: "遭遇战失利",
  PLAYER_REJECTED: "玩家拒绝了提案",
  GENERIC_REPLAN_LIMIT: "已达到重新规划上限",
  UNSUPPORTED: "不支持的目标",
  NEEDS_CLARIFICATION: "需要澄清",
  ACCEPTED: "已接受",
  AVAILABLE: "可用",
  UNAVAILABLE: "不可用",
  UNKNOWN: "未知",
  LOCKED: "锁定",
  KNOWN: "已知",
  HIDDEN: "隐藏",
  VISIBLE: "可见",
  ONLINE: "在线",
  DISCONNECTED: "失联",
  ENTERED: "已进入",
  INACTIVE: "未激活",
  IDLE: "空闲",
  PLANNED: "已规划",
  LOGISTICS: "物流",
  INSPECT: "检查",
  TRAVEL: "移动",
  TRANSPORT_RESOURCE: "运输资源",
  RELAY_MESSAGE: "传递信息",
  SURVEY_RESOURCES: "调查资源",
  SUPPLY_POWER: "供电",
  DEPLOY_HEAVY_ENGINEERING_SUPPORT: "部署重型工程支援",
  REPAIR_COMMUNICATIONS: "修复通信",
  CLEAR_TRANSPORT: "清理交通",
  RULE: "规则",
  ACTION: "行动",
  STATE: "状态",
  NODE: "节点",
  ACTOR: "参与者",
  REGION: "区域",
  FACILITY: "设施",
  RESOURCE: "资源",
  RELATION: "关系",
  DERIVED: "派生结果",
  PUBLIC_REFERENCE: "公共引用",
  ACTION_SOURCE: "行动来源",
  ACTOR_REGION: "参与者所在区域",
  SET_ACTOR_COMMAND_REACHABILITY: "设置参与者指挥可达性",
  SET_RELATION_VISIBILITY: "设置关系可见性",
  SET_REGION_RESOURCE_VISIBILITY: "设置区域资源可见性",
  SET_RESOURCE_POOL_VISIBILITY: "设置资源池可见性",
  SET_RESOURCE_POOL_AVAILABILITY: "设置资源池可用性",
  REVEAL_TARGET_REGION_FACILITY_FACTS: "揭示目标区域设施事实",
  NONE: "无",
  LOCAL_TARGET: "本地目标",
  FACILITY_REGION: "设施所在区域",
  TRANSPORT_ENDPOINT: "交通端点",
  ACTOR_CURRENT_REGION: "参与者当前区域",
  CURRENT_TARGET_REGION: "当前目标区域",
  FACT: "事实",
  DERIVED_STATE: "派生状态",
  RESOURCE_AT_LEAST: "资源达到阈值",
  IMMEDIATE: "立即执行",
  ASYNC: "异步结算",
  PREFLIGHT: "执行前检查",
  RESOLVE: "结算",
  STRING: "文本",
  ENUM: "枚举",
  INTEGER: "整数",
  BOOLEAN: "布尔值",
  ALL: "全部满足",
  ANY: "任一满足",
  NOT: "取反",
  EQ: "等于",
  NE: "不等于",
  LT: "小于",
  LTE: "小于等于",
  GT: "大于",
  GTE: "大于等于",
  LITERAL: "固定值",
  PARAMETER: "参数",
  PLAN: "规划",
  EXECUTE_ACTION: "执行行动",
  INSPECT_STATE: "检查状态",
  FACT_EQUALS: "事实等于",
  FACT_NOT_EQUALS: "事实不等于",
  FACT_IN: "事实属于集合",
  FACT_COMPARE: "事实比较",
  RESOURCE_COMPARE: "资源比较",
  PARAMETER_COMPARE: "参数比较",
  NODE_VISIBLE: "节点可见",
  NODE_ACCESSIBLE: "节点可访问",
  RELATION_EXISTS: "关系存在",
  SET_FACT: "设置事实",
  REVEAL_FACT: "揭示事实",
  HIDE_FACT: "隐藏事实",
  REVEAL_NODE: "揭示节点",
  HIDE_NODE: "隐藏节点",
  SET_NODE_ACCESS: "设置节点访问状态",
  ADJUST_RESOURCE: "调整资源",
  RESERVE_RESOURCE: "预留资源",
  RELEASE_RESOURCE: "释放资源",
  EMIT_OUTCOME: "产生成功结果",
  EMIT_FAILURE: "产生失败结果",
  WRITE_MEMORY_EVENT: "写入记忆事件",
  SOURCE: "来源节点",
  TARGET: "目标节点",
  EXPLICIT: "显式",
  CURRENT_TARGET: "当前目标",
};

export const sectionLabels: Record<string, string> = {
  "node-types": "节点类型",
  "world-entities": "世界实体",
  "relation-types": "关系类型",
  relations: "关系实例",
  resources: "资源定义",
  roles: "角色",
  interactions: "交互",
  "derived-states": "派生状态",
  initialization: "初始化",
  "goal-resolution": "目标解析",
  "public-knowledge": "公共知识",
  "public-references": "公共引用",
  overview: "概览",
  world: "世界总览",
  actors: "参与者",
  actions: "行动",
  rules: "规则",
  planning: "规划策略",
  "initial-state": "初始状态",
  validation: "验证与发布",
};

export const editorTaxonomyGroups = [
  { label: "场景基础", items: ["overview"] },
  { label: "世界模型", items: ["world", "node-types", "world-entities", "relation-types", "relations", "resources"] },
  { label: "参与者与交互", items: ["roles", "actors", "interactions"] },
  { label: "行动系统", items: ["actions", "rules"] },
  { label: "目标系统", items: ["derived-states", "goal-resolution"] },
  { label: "运行配置", items: ["initialization", "planning"] },
  { label: "公开信息", items: ["public-knowledge", "public-references"] },
  { label: "发布", items: ["validation"] },
] as const;

export const editorSectionTaxonomy: Record<string, { category: string; label: string }> = Object.fromEntries(
  editorTaxonomyGroups.flatMap((group) => group.items.map((section) => [
    section,
    { category: group.label, label: sectionLabels[section] ?? section },
  ])),
);

export const kindLabels: Record<string, string> = {
  relation_type: "关系类型",
  relation: "关系实例",
  derived_state: "派生状态",
  public_reference: "公共引用",
  node_type: "节点类型",
  node: "节点",
  resource: "资源",
  interaction: "交互能力",
  role: "角色",
  actor: "参与者",
  action: "行动",
  rule: "规则",
};

const fieldLabels: Record<string, string> = {
  unit: "单位",
  display_unit: "显示单位",
  value_labels: "值标签",
  key: "稳定键",
  name: "显示名称",
  description: "说明",
  node_type_key: "节点类型",
  initial_access: "初始访问状态",
  initial_visibility: "初始可见性",
  interaction_keys: "交互能力",
  facts: "事实",
  relations: "关系",
  initial_value: "初始值",
  minimum: "最小值",
  maximum: "最大值",
  reservation_supported: "支持预留",
  capabilities: "能力",
  role_key: "角色",
  persona: "人物设定",
  doctrine: "行为准则",
  initial_node_key: "初始节点",
  allowed_action_keys: "允许的行动",
  authority_policy: "权限策略",
  autonomous_limits: "自主权限上限",
  approval_required_values: "需要批准的值",
  required_interaction_key: "所需交互能力",
  execution_mode: "执行方式",
  parameters: "参数",
  allowed_actor_capabilities: "参与者所需能力",
  expected_outcomes: "预期结果",
  planning: "规划元数据",
  terminal_effects: "终局效果",
  supporting_effects: "辅助效果",
  success_outcome_codes: "成功结果代码",
  wait_success_outcome_codes: "等待成功结果代码",
  hints: "规划提示",
  phase: "阶段",
  action_key: "行动",
  priority: "优先级",
  condition: "条件",
  conditions: "子条件",
  effects: "效果",
  kind: "类型",
  operator: "比较方式",
  source: "值来源",
  value: "值",
  values: "可选值",
  fact_key: "事实",
  node_key: "节点",
  resource_key: "资源",
  parameter_key: "参数",
  completion_requirements: "完成要求",
  prerequisites: "前置条件",
  requirements: "要求",
  subsumes: "包含的目标",
  goal_aliases: "目标别名",
  goal_examples: "目标示例",
  goal_target_values: "目标值",
  accepted_values: "可接受值",
  start_node_key: "起始节点",
  primary_actor_key: "主要参与者",
  goal_resolution: "目标解析",
  instructions: "全局规划指引",
  recovery_hints: "失败恢复策略",
  allowed_values: "允许值",
  required: "必填",
  code: "代码",
  success: "是否成功",
  retryable: "可重试",
  outcome_code: "结果代码",
  metadata: "元数据",
  schema_version: "结构版本",
  engine_contract: "引擎契约",
  world: "世界",
  node_types: "节点类型",
  nodes: "节点",
  resources: "资源",
  interactions: "交互能力",
  actors: "参与者",
  roles: "角色",
  actor_profiles: "参与者",
  actions: "行动",
  rules: "规则",
  initialization: "初始化",
  allow_llm_fallback: "允许模型辅助解析",
  clarification_prompt: "澄清提示",
  quick_inputs: "快捷输入",
  relation_type_key: "关系类型",
  source_node_key: "来源节点",
  target_node_key: "目标节点",
  direction: "方向",
  relation_direction: "关系方向",
  amount: "数量",
  literal: "固定值",
  multiplier: "倍数",
  memory_key: "记忆键",
  memory_content: "记忆内容",
  failure_code: "失败代码",
  message: "消息",
};

export function uiLabel(value: string | null | undefined): string {
  if (!value) return "—";
  return labels[value] ?? value.replaceAll("_", " ");
}

const enumLabels: Record<string, Record<string, string>> = {
  generic: {
    AVAILABLE: "可用",
    UNAVAILABLE: "不可用",
    VISIBLE: "可见",
    HIDDEN: "隐藏",
    KNOWN: "已知",
    UNKNOWN: "未知",
    LOCKED: "锁定",
    ONLINE: "在线",
    DISCONNECTED: "失联",
    ENTERED: "已进入",
    ACTIVE: "进行中",
    INACTIVE: "未激活",
    IDLE: "空闲",
    PLANNED: "已规划",
    EXPLICIT: "显式",
    DEFAULT: "系统默认",
    LEGACY_FALLBACK: "兼容回退",
    ENGINE: "引擎默认",
    DERIVED: "派生结果",
  },
  access: { AVAILABLE: "可用", LOCKED: "锁定" },
  visibility: { VISIBLE: "可见", KNOWN: "已知", HIDDEN: "隐藏" },
  reachability: { ONLINE: "在线", DISCONNECTED: "失联" },
  availability: { AVAILABLE: "可用", UNAVAILABLE: "不可用" },
  value_type: { STRING: "文本", ENUM: "枚举", INTEGER: "整数", BOOLEAN: "布尔值" },
  source: {
    EXPLICIT: "显式配置",
    DEFAULT: "系统默认",
    LEGACY_FALLBACK: "兼容回退",
    ENGINE: "引擎默认",
    DERIVED: "派生结果",
    MISSING: "缺失",
    INVALID: "无效",
  },
};

export function displayEnumValue(enumType: string, value: string | null | undefined): string {
  if (!value) return "—";
  return enumLabels[enumType]?.[value] ?? uiLabel(value);
}

export function taskExplanationLabel(status: string, explanation: string | null): string | null {
  if (!explanation) return null;
  const explanationLabel = uiLabel(explanation);
  return explanationLabel === uiLabel(status) ? null : explanationLabel;
}

export function fieldLabel(value: string): string {
  return fieldLabels[value] ?? value.replaceAll("_", " ");
}

// Editor-only copy lives here so specialized renderers do not each grow a
// second, partially translated label catalog. Stable keys and enum values are
// still kept in their authored machine form; this map only controls visible
// presentation text.
const editorLabels: Record<string, string> = {
  "Scenario key": "场景键",
  "Scenario name": "场景名称",
  Description: "说明",
  "Locality contract": "局部性契约",
  Enabled: "启用",
  "Scoped resources": "按区域管理资源",
  "Region node type": "区域节点类型",
  "Facility node type": "设施节点类型",
  "Transport node type": "交通节点类型",
  "Located-in relation type": "归属关系类型",
  "Endpoint relation type": "端点关系类型",
  "Passability fact": "可通行事实",
  "Canonical value": "规范值",
  "Value labels": "值标签",
  "Add value label": "添加值标签",
  "Display label": "显示标签",
  "Add fact": "添加事实",
  Facts: "事实",
  "Child conditions": "子条件",
  "Add initial state": "添加初始状态",
  "Resource initial states": "资源初始状态",
  "Resource initial state": "资源初始状态",
  "Resource pools (initialization, not definitions)": "资源池（初始化数据，非资源定义）",
  "Add pool": "添加资源池",
  "Region resource knowledge": "区域资源知识",
  "Add region state": "添加区域状态",
  "Planning instructions": "全局规划指引",
  "Recovery hint": "失败恢复策略",
  "Add recovery hint": "新增失败恢复策略",
  "Allow LLM fallback": "允许模型辅助回退",
  "Clarification prompt": "澄清提示",
  "Quick inputs": "快捷输入",
  "World goal state catalog": "世界目标状态目录",
  "Resource source hints": "资源来源提示",
  "Add source hint": "添加来源提示",
  "Resource source hint": "资源来源提示",
  "Public term": "公共术语",
  "Reference type": "引用类型",
  "Reference key": "引用键",
  "Collection item": "集合项",
  "Singleton config": "单例配置",
  "Public knowledge": "公共知识",
  "Authority policy": "权限策略",
  "Reveal target region facility facts": "揭示目标区域设施事实",
  "Add requirement": "添加要求",
  "Add prerequisite": "添加前置条件",
  "Add knowledge gate": "添加知识门槛",
  "Completion requirements": "完成要求",
  "Prerequisites": "前置条件",
  "Requirements (Advanced identity list)": "要求（高级身份列表）",
  "Goal aliases": "目标别名",
  "Goal examples": "目标示例",
  "Dependency kind": "依赖类型",
  Dependencies: "依赖",
  "Planning guidance": "全局规划指引",
  "Add relation": "添加关系",
  "Add relation type": "添加关系类型",
  "Add resource": "添加资源",
  "Add actor": "添加参与者",
  "Add action": "添加行动",
  "Add rule": "添加规则",
  "Add derived state": "添加派生状态",
  "Add binding": "添加绑定",
  "Add dependency": "添加依赖",
  "Add outcome": "添加结果",
  "Add parameter": "添加参数",
  "Add target role": "添加目标角色",
  Action: "行动",
  "Candidate regions": "候选区域",
  Default: "默认值",
  Dependency: "依赖",
  Direction: "方向",
  Facility: "设施",
  "Goal addressable": "可作为目标",
  "Goal metadata": "目标元数据",
  "Goal target values": "目标值",
  "Delete fact": "删除事实",
  "Allowed values (Advanced JSON)": "允许值（高级 JSON）",
  "Goal required slots": "目标必需槽位",
  Phase: "阶段",
  "Primary region": "主要区域",
  Priority: "优先级",
  Prerequisite: "前置条件",
  Requirement: "要求",
  "Required role": "所需角色",
  Trigger: "触发方式",
  "Relation exists": "关系存在",
  "Resource scope": "资源作用域",
  Literal: "固定值",
  Multiplier: "倍数",
  "Memory key": "记忆键",
  "Memory content": "记忆内容",
  "Public reference": "公共引用",
  "Derived state": "派生状态",
  "Failure code": "失败代码",
  Hint: "提示",
  "Resource pool": "资源池",
  Pool: "资源池",
  "Survey completed": "已完成调查",
  "Survey discoverable": "可由调查发现",
  Reserved: "已预留",
  "Add availability requirement": "添加可用性要求",
  "Availability requirement": "可用性要求",
  "Target node types": "目标节点类型",
  "Target Fact effect": "目标事实效果",
  "Target and relation semantics": "目标与关系语义",
  "Value type": "值类型",
  Code: "代码",
  Success: "成功",
  "Resource definitions": "资源定义",
  "Resource definitions 在 World 中维护；resource initial states、pools 和 region knowledge 属于初始化数据，当前保留为 Advanced 结构。": "资源定义在世界模型中维护；资源初始状态、资源池和区域资源知识属于初始化数据，当前以高级结构保留。",
  "Planning instructions 已提供 typed 文本数组入口；recovery hints 在 Phase 3 Rule/Planning 表单中展开。": "全局规划指引已提供结构化文本数组入口；失败恢复策略会在规则与规划表单中展开。",
  Key: "稳定键",
  Name: "显示名称",
  "Start node": "起始节点",
  "Primary actor": "主要参与者",
  "Pool key": "资源池键",
  Quantity: "数量",
  Visibility: "可见性",
  "Inventory visibility": "库存可见性",
  "Pool visibility": "资源池可见性",
  Availability: "可用性",
  "Advanced structure": "高级结构",
  Advanced: "高级结构",
  "Summary label": "摘要标签",
  "Detail label": "详情标签",
  Add: "添加",
  Remove: "移除",
  Delete: "删除",
  "Condition kind": "条件类型",
  "Effect kind": "效果类型",
  "Selector kind": "选择器类型",
  "Value source": "值来源",
  "Amount source": "数量来源",
  "Relation type": "关系类型",
  "Relation direction": "关系方向",
  "Anchor node": "锚点节点",
  "Required fact": "所需事实",
  Node: "节点",
  Fact: "事实",
  FACT: "事实",
  DERIVED_STATE: "派生状态",
  RESOURCE_AT_LEAST: "资源达到阈值",
  RELATED: "关联对象",
  CURRENT_TARGET: "当前目标",
  EXPLICIT: "显式",
  Resource: "资源",
  "Scope node": "作用域节点",
  Operator: "比较方式",
  Value: "值",
  "Accepted values": "可接受值",
  "Parameter key": "参数键",
  "Parameter semantics": "参数语义",
  Access: "访问状态",
  "Outcome code": "结果代码",
  Message: "消息",
  Retryable: "可重试",
  Actor: "参与者",
  Reachability: "可达性",
  Relation: "关系",
  Region: "区域",
  "Required value": "要求值",
  "Allowed values": "允许值",
  "Allowed capabilities": "允许的能力",
  "Required interaction": "所需交互能力",
  "Required actor role": "所需参与者角色",
  "Target kind": "目标类型",
  "Target semantic reference": "目标语义引用",
  "Execution mode": "执行方式",
  Behavior: "行为",
  Locality: "局部性",
  "Source relation type": "来源关系类型",
  Required: "必填",
  Minimum: "最小值",
  Maximum: "最大值",
  "Semantic reference": "语义引用",
  "Condition": "条件",
  "Effect": "效果",
  "Fact reference": "事实引用",
  "Knowledge gate": "知识门槛",
  "Resource availability requirement": "资源可用性要求",
  "Terminal Fact effects": "终局事实效果",
  "Target-relative Fact effects": "目标相对事实效果",
  "Supporting Fact effects": "辅助事实效果",
  "Success outcomes": "成功结果",
  "Wait success outcomes": "等待成功结果",
  "Planner hints": "规划提示",
  "Action planning projection": "行动规划投影",
  "Action planning": "行动规划",
  Projection: "投影",
  "Autonomous limit": "自主权限上限",
  "Approval-required values": "需要批准的值",
  "Add doctrine": "添加行为准则",
  "Add limit": "添加权限上限",
  "Add approval rule": "添加审批规则",
  Parameters: "参数",
  Parameter: "参数",
  "Expected outcomes": "预期结果",
  Outcome: "结果",
  "Target actor roles": "目标参与者角色",
  "Target actor role": "目标参与者角色",
  Target: "目标",
  "Operation bindings": "操作绑定",
  "Operation binding": "操作绑定",
  "Slot role": "槽位角色",
  Source: "来源",
  "Condition AST": "条件树",
  Effects: "效果",
  "Add condition": "添加条件",
  "Add effect": "添加效果",
  "Remove condition": "移除条件",
  "Requirement kind": "要求类型",
  Requirements: "要求",
  Subsumes: "包含目标",
  "Available value": "可用值",
  "Unavailable value": "不可用值",
  Instructions: "规划指令",
  "Recovery hints": "失败恢复策略",
  Term: "术语",
};

export function editorLabel(value: string): string {
  if (editorLabels[value]) return editorLabels[value];
  const indexed = value.match(/^(.*) (\d+)$/);
  if (indexed && editorLabels[indexed[1]]) return `${editorLabels[indexed[1]]} ${indexed[2]}`;
  return fieldLabel(value);
}

export function stepDescription(value: string): string {
  if (value.startsWith("Execute ")) return `执行：${value.slice(8)}`;
  if (value.startsWith("Wait for ")) return `等待结算：${value.slice(9)}`;
  return value;
}

export function resultLabel(value: string | null): string | null {
  if (!value) return null;
  if (value === "Completed") return "已完成";
  return uiLabel(value.toUpperCase().replaceAll(" ", "_"));
}

const diagnosticLabels: Record<string, string> = {
  SCENARIO_DOCUMENT_SCHEMA_INVALID: "字段结构或类型不符合场景定义要求。",
  SCENARIO_DOCUMENT_SCHEMA_UNSUPPORTED: "不支持此场景结构版本。",
  SCENARIO_ENGINE_CONTRACT_UNAVAILABLE: "当前平台不支持此通用引擎契约。",
  SCENARIO_OBJECTIVE_REQUIRED: "可发布的场景至少需要一个目标。",
  SCENARIO_ACTION_REQUIRED: "可发布的场景至少需要一个行动。",
  SCENARIO_MINIMUM_PLAYABLE_REQUIRED: "没有已结算行动的规划效果能够推进目标要求。",
  SCENARIO_ACTION_WITHOUT_RESOLVE_RULE: "此行动没有对应的结算规则。",
};

export function diagnosticMessage(code: string, fallback: string): string {
  return diagnosticLabels[code] ?? fallback;
}

export function goalSubmissionErrorText(
  error: unknown,
  fallback = "\u76ee\u6807\u89e3\u6790\u6682\u65f6\u5931\u8d25\uff0c\u8bf7\u91cd\u65b0\u89e3\u6790\u3002",
): string {
  void error;
  return fallback;
}

const confirmLifecycleMessages: Record<string, string> = {
  GOAL_DRAFT_NOT_FOUND: "这个目标确认已失效，请重新解析目标。",
  GOAL_DRAFT_SUPERSEDED: "这个目标确认已失效，请重新解析目标。",
  AGENT_TASK_ALREADY_ACTIVE: "当前已有进行中的任务，暂时无法确认新的目标。",
  GOAL_DRAFT_CONFIRMATION_CONFLICT: "目标确认发生冲突，请重新尝试。",
};

const confirmSystemCodes = new Set([
  "GOAL_DRAFT_CONFIRMATION_INCOMPLETE",
  "GENERIC_SESSION_SCOPE_INVALID",
  "PLAY_SESSION_NOT_FOUND",
  "INTERNAL_ERROR",
  "REQUEST_FAILED",
]);

export function confirmGoalErrorText(
  error: unknown,
  fallback = "目标确认暂时失败，请重新尝试。",
): string {
  if (!error || typeof error !== "object") return fallback;
  const code = "code" in error && typeof error.code === "string" ? error.code : null;
  if (!code) return fallback;
  const lifecycleMessage = confirmLifecycleMessages[code];
  if (lifecycleMessage) return lifecycleMessage;
  if (confirmSystemCodes.has(code) || code.startsWith("FORMAL_GOAL_")) return fallback;
  return fallback;
}

export function errorText(error: unknown, fallback = "操作失败，请稍后重试。") {
  if (!error || typeof error !== "object") return fallback;
  const code = "code" in error && typeof error.code === "string" ? error.code : null;
  return code ? `${uiLabel(code)}（${code}）` : fallback;
}
